const PREFIX = 'cart/'

export const cartActionTypes = {
    INCREASE_QUANTITY: PREFIX + 'INCREASE_QUANTITY',
    DECREASE_QUANTITY: PREFIX + 'DECREASE_QUANTITY',
    GET_ALL_PRODUCT: PREFIX + 'GET_ALL_PRODUCT',
    GET_NUMBER_CART: PREFIX + 'GET_NUMBER_CART',
    ADD_CART: PREFIX + 'ADD_CART',
    UPDATE_CART: PREFIX + 'UPDATE_CART',
    DELETE_CART: PREFIX + 'DELETE_CART',

}