const PREFIX = 'product/';

export const productActionTypes = {
    FETCH_PRODUCT_START: PREFIX + 'FETCH_PRODUCT_START',
    FETCH_PRODUCT_SUCCESS: PREFIX + 'FETCH_PRODUCT_SUCCESS',
    FETCH_PRODUCT_ERROR: PREFIX + 'FETCH_PRODUCT_ERROR',
}